
//BOOKMARK TABS CONSTS
export const CREATE_MULTIPLE_BOOKMARKS_REQUEST = 'CREATE_MULTIPLE_BOOKMARKS_REQUEST';

//CHECKED TABS CONSTS
export const CHECK_TAB = 'CHECK_TAB';
export const UNCHECK_TAB = 'UNCHECK_TAB';
export const CHECK_WINDOW = 'CHECK_WINDOW';
export const UNCHECK_WINDOW = 'UNCHECK_WINDOW';
export const UNCHECK_MULTIPLE = 'UNCHECK_MULTIPLE';
export const CLEAR = 'CLEAR';
export const UPDATE_WINDOW_ID = 'UPDATE_WINDOW_ID';
export const UPDATE_MULTIPLE_WINDOW_ID ='UPDATE_MULTIPLE_WINDOW_ID';
