
//BOOKMARK TABS CONSTS
export const CREATE_MULTIPLE_BOOKMARKS_REQUEST = 'CREATE_MULTIPLE_BOOKMARKS_REQUEST';

//WINDOW CONSTS
export const CREATE_WINDOW_REQUEST = 'CREATE_WINDOW_REQUEST';
export const SET_WINDOWS_REQUEST = 'SET_WINDOWS_REQUEST';
export const UPDATE_TABS_ORDER_REQUEST = 'UPDATE_TABS_ORDER_REQUEST';
export const REMOVE_WINDOW_REQUEST = 'REMOVE_WINDOW_REQUEST';

//TABS CONSTS
export const CREATE_TAB_REQUEST = 'CREATE_TAB_REQUEST';
export const MUTE_TAB_REQUEST = 'MUTE_TAB_REQUEST';
export const PIN_TAB_REQUEST = 'PIN_TAB_REQUEST';
export const PIN_MULTIPLE_TABS_REQUEST = 'PIN_MULTIPLE_TABS_REQUEST';
export const SET_TAB_ACTIVE_REQUEST = 'SET_TAB_ACTIVE_REQUEST';
export const MOVE_TAB_REQUEST = 'MOVE_TAB_REQUEST';
export const MOVE_TABS_REQUEST = 'MOVE_TABS_REQUEST';
export const ATTACH_TAB_REQUEST ='ATTACH_TAB_REQUEST';
export const REMOVE_TAB_REQUEST = 'REMOVE_TAB_REQUEST';
export const REMOVE_TABS_REQUEST = 'REMOVE_TABS_REQUEST';